"use client";

import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  LayoutDashboard, FileText, BarChart3, ShieldAlert, Truck,
  ShoppingBag, Bot, Bell, Settings, ChevronDown,
  Send, FileUp, CheckCircle2, Sparkles, AlertTriangle
} from "lucide-react";

/* ─── Sidebar Items ─── */
const sidebarItems = [
  { icon: LayoutDashboard, label: "Dashboard", active: true },
  { icon: FileText, label: "ESG Reports", active: false },
  { icon: BarChart3, label: "Carbon Analysis", active: false },
  { icon: ShieldAlert, label: "Greenwash Detect", active: false },
  { icon: Truck, label: "Suppliers", active: false },
  { icon: ShoppingBag, label: "Marketplace", active: false },
  { icon: Bot, label: "EcoBot", active: false },
];

/* ─── Stat Cards ─── */
const statCards = [
  { label: "Total Emissions", value: "24,531", unit: "tCO₂e", change: "↓ 8.6%", positive: true, color: "#22c55e" },
  { label: "Scope 3 Share", value: "72%", unit: "of total", change: null, positive: true, color: "#8b5cf6" },
  { label: "Suppliers Monitored", value: "1,248", unit: "", change: "↑ 120 new", positive: true, color: "#3b82f6" },
  { label: "Green Credit Score", value: "92", unit: "/100", change: "Excellent", positive: true, color: "#22c55e" },
];

/* ─── Emission Sources ─── */
const emissionSources = [
  { name: "Raw Materials", value: "8,452", pct: "34.5%", trend: "↑ 12%", up: true },
  { name: "Manufacturing", value: "6,210", pct: "25.3%", trend: "↑ 4%", up: true },
  { name: "Upstream Transport", value: "4,912", pct: "20.0%", trend: "↑ 8%", up: true },
  { name: "Packaging", value: "2,105", pct: "8.6%", trend: "↓ 3%", up: false },
  { name: "Business Travel", value: "1,342", pct: "5.5%", trend: "↓ 1%", up: false },
];

/* ─── Breakdown Data ─── */
const breakdownData = [
  { label: "Purchased Goods & Services", pct: 45.2, color: "#22c55e" },
  { label: "Upstream", pct: 20.1, color: "#3b82f6" },
  { label: "Business Travel", pct: 12.4, color: "#8b5cf6" },
  { label: "Waste Generated", pct: 8.7, color: "#f59e0b" },
  { label: "Others", pct: 13.6, color: "#6b7280" },
];

/* ─── Recent Activity ─── */
const recentActivity = [
  { icon: FileUp, label: "Supplier_Invoice.pdf", sub: "uploaded by Rohit Sharma", color: "#ef4444" },
  { icon: CheckCircle2, label: "Transport_Data.csv", sub: "processed successfully", color: "#22c55e" },
  { icon: Sparkles, label: "BRSR Report Q1.pdf", sub: "generated by AI Agent", color: "#3b82f6" },
  { icon: AlertTriangle, label: "Greenwashing Risk", sub: "alert resolved", color: "#f59e0b" },
];

/* ─── Agent Actions ─── */
const agentActions = [
  "Generate BRSR Report",
  "Analyze Greenwashing Risk",
  "Find Emission Reduction Opportunities",
  "Compare Suppliers",
];

/* ─── Mini Sparkline ─── */
function MiniSparkline() {
  const points = [40, 35, 45, 30, 50, 42, 55, 48, 60, 52, 58, 65];
  const h = 32, w = 100;
  const max = Math.max(...points);
  const pathD = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w;
    const y = h - (p / max) * h;
    return `${i === 0 ? "M" : "L"} ${x} ${y}`;
  }).join(" ");
  
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-8" preserveAspectRatio="none">
      <defs>
        <linearGradient id="sparkGrad" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0%" stopColor="#22c55e" stopOpacity="0.2" />
          <stop offset="100%" stopColor="#22c55e" stopOpacity="0" />
        </linearGradient>
      </defs>
      <path d={`${pathD} L ${w} ${h} L 0 ${h} Z`} fill="url(#sparkGrad)" />
      <path d={pathD} fill="none" stroke="#22c55e" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" className="opacity-75" />
    </svg>
  );
}

/* ─── Donut Chart ─── */
function MiniDonut() {
  const r = 36, cx = 44, cy = 44, c = 2 * Math.PI * r;
  let offset = 0;
  return (
    <div className="relative w-[88px] h-[88px] shrink-0">
      <svg viewBox="0 0 88 88" className="w-full h-full -rotate-90">
        {breakdownData.map((d) => {
          const len = (d.pct / 100) * c;
          const dash = `${len} ${c - len}`;
          const el = (
            <circle key={d.label} cx={cx} cy={cy} r={r} fill="none" stroke={d.color}
              strokeWidth="7" strokeDasharray={dash} strokeDashoffset={-offset}
              strokeLinecap="round" className="opacity-70" />
          );
          offset += len;
          return el;
        })}
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-[10px] font-medium font-mono text-text-primary tracking-tight">24,531</span>
        <span className="text-[6px] text-text-muted font-light uppercase tracking-wider scale-90">tCO₂e</span>
      </div>
    </div>
  );
}

/* ═══ MAIN COMPONENT ═══ */
export default function ACTRMEngine() {
  const [activeSource, setActiveSource] = useState(0);
  const [agentTyping, setAgentTyping] = useState(false);

  useEffect(() => {
    const t = setInterval(() => setActiveSource(p => (p + 1) % emissionSources.length), 3000);
    return () => clearInterval(t);
  }, []);

  useEffect(() => {
    const t = setInterval(() => { setAgentTyping(true); setTimeout(() => setAgentTyping(false), 1500); }, 5000);
    return () => clearInterval(t);
  }, []);

  return (
    <div className="w-full max-w-[760px] select-none font-sans" style={{ fontSize: "11.8px" }}>
      <div className="rounded-xl overflow-hidden border border-white/[0.04] bg-[#0c0c0e] shadow-2xl shadow-black/40">

        {/* ═══ TOP BAR ═══ */}
        <div className="flex items-center justify-between px-3 py-2 border-b border-white/[0.03] bg-[#101012]">
          <div className="flex items-center gap-2">
            <div className="h-4 w-4 rounded bg-accent/10 border border-accent/20 flex items-center justify-center">
              <LayoutDashboard className="h-2.5 w-2.5 text-accent opacity-80" />
            </div>
            <span className="font-medium text-text-primary text-[10px] tracking-tight">Dashboard</span>
            <span className="text-text-muted opacity-50">·</span>
            <span className="text-text-muted font-light">Overview</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 rounded bg-surface/80 border border-white/[0.04] text-[8px] text-text-secondary font-light flex items-center gap-1">
              Acme Corporation <ChevronDown className="h-2 w-2 opacity-60" />
            </span>
            <span className="px-2 py-0.5 rounded bg-surface/80 border border-white/[0.04] text-[8px] text-text-secondary font-light flex items-center gap-1">
              This Quarter <ChevronDown className="h-2 w-2 opacity-60" />
            </span>
            <Bell className="h-3 w-3 text-text-muted opacity-70" />
            <Settings className="h-3 w-3 text-text-muted opacity-70" />
          </div>
        </div>

        <div className="flex">
          {/* ═══ SIDEBAR ═══ */}
          <div className="w-10 shrink-0 border-r border-white/[0.03] bg-[#0e0e10] py-2 flex flex-col items-center gap-1">
            {sidebarItems.map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.label} title={item.label}
                  className={`h-7 w-7 rounded-lg flex items-center justify-center cursor-pointer transition-all
                    ${item.active ? "bg-accent/5 border border-accent/10" : "hover:bg-white/[0.03]"}`}>
                  <Icon className={`h-3 w-3 ${item.active ? "text-accent opacity-90" : "text-text-muted opacity-70"}`} />
                </div>
              );
            })}
          </div>

          {/* ═══ MAIN CONTENT ═══ */}
          <div className="flex-1 min-w-0 bg-[#0a0a0c]">

            {/* ── Stat Cards Row ── */}
            <div className="grid grid-cols-4 gap-2 p-2">
              {statCards.map((s, i) => (
                <motion.div key={s.label}
                  initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05, duration: 0.3 }}
                  className="rounded-lg bg-surface/40 border border-white/[0.03] p-2"
                >
                  <p className="text-[8px] text-text-muted font-light tracking-wide mb-1">{s.label}</p>
                  <div className="flex items-baseline gap-0.5">
                    <span className="text-[13px] font-medium font-mono text-text-primary tracking-tight">{s.value}</span>
                    <span className="text-[7px] text-text-muted font-light">{s.unit}</span>
                  </div>
                  {s.change && (
                    <span className={`text-[7px] mt-0.5 font-light inline-block ${s.positive ? "text-accent/90" : "text-danger"}`}>
                      {s.change}
                    </span>
                  )}
                </motion.div>
              ))}
            </div>

            {/* ── Middle Row: Chart + Donut + Agent ── */}
            <div className="grid grid-cols-12 gap-2 px-2">
              {/* Emissions Trend */}
              <div className="col-span-5 rounded-lg bg-surface/40 border border-white/[0.03] p-2 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[9px] font-medium text-text-primary tracking-tight">Emissions Trend</span>
                    <span className="text-[6px] text-text-muted px-1.5 py-0.5 rounded bg-surface/50 border border-white/[0.03] uppercase tracking-wider">Monthly</span>
                  </div>
                  <MiniSparkline />
                </div>
                <div className="flex flex-wrap gap-2 mt-1.5">
                  {["Total", "Scope 1", "Scope 2", "Scope 3"].map((l, i) => (
                    <span key={l} className="flex items-center gap-1 text-[7px] text-text-muted font-light">
                      <span className="w-1.5 h-1.5 rounded-full opacity-80" style={{ background: ["#22c55e","#3b82f6","#8b5cf6","#f59e0b"][i] }} />
                      {l}
                    </span>
                  ))}
                </div>
              </div>

              {/* Emissions Breakdown */}
              <div className="col-span-3 rounded-lg bg-surface/40 border border-white/[0.03] p-2 flex flex-col">
                <span className="text-[9px] font-medium text-text-primary tracking-tight block mb-1">Breakdown</span>
                <div className="flex items-center gap-2 flex-1">
                  <MiniDonut />
                  <div className="flex flex-col gap-0.5 min-w-0 flex-1">
                    {breakdownData.slice(0, 4).map((d) => (
                      <span key={d.label} className="flex items-center gap-1 text-[6.5px] text-text-muted font-light truncate">
                        <span className="w-1 h-1 rounded-full shrink-0" style={{ background: d.color }} />
                        <span className="truncate">{d.label}</span>
                        <span className="font-mono ml-auto shrink-0 opacity-80">{d.pct}%</span>
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* AI ESG Agent */}
              <div className="col-span-4 rounded-lg bg-surface/40 border border-white/[0.03] p-2 flex flex-col">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[9px] font-medium text-text-primary tracking-tight">AI ESG Agent</span>
                  <span className="flex items-center gap-1 text-[6.5px] text-accent/90 font-light">
                    <span className="pulse-dot !w-[3px] !h-[3px]" /> Active
                  </span>
                </div>
                <div className="rounded bg-[#0c0c0e] border border-white/[0.03] p-1.5 mb-1.5 text-[8px] text-text-secondary font-light leading-relaxed">
                  Hi! I&apos;m your AI ESG Agent. How can I help you today?
                </div>
                <div className="flex flex-col gap-1 flex-1">
                  {agentActions.slice(0, 3).map((a) => (
                    <div key={a} className="flex items-center gap-1.5 px-1.5 py-1 rounded bg-[#0c0c0e] border border-white/[0.03] text-[6.5px] text-text-secondary font-light cursor-pointer hover:border-accent/10 hover:text-text-primary transition-colors truncate">
                      <Sparkles className="h-2 w-2 text-accent/50 shrink-0" />
                      <span className="truncate">{a}</span>
                    </div>
                  ))}
                </div>
                <div className="mt-1.5 flex items-center gap-1 rounded bg-[#0c0c0e] border border-white/[0.03] px-1.5 py-0.5">
                  <span className="text-[6.5px] text-text-muted font-light flex-1">
                    {agentTyping ? (
                      <span className="text-accent/80 font-normal">Analyzing data streams...</span>
                    ) : "Query sustainability logs..."}
                  </span>
                  <Send className="h-2 w-2 text-text-muted opacity-60" />
                </div>
              </div>
            </div>

            {/* ── Bottom Row: Sources Table + Recommendations ── */}
            <div className="grid grid-cols-12 gap-2 p-2">
              {/* Top Emission Sources */}
              <div className="col-span-7 rounded-lg bg-surface/40 border border-white/[0.03] p-2">
                <span className="text-[9px] font-medium text-text-primary tracking-tight block mb-1.5">Top Sources</span>
                <table className="w-full">
                  <thead>
                    <tr className="text-[6.5px] text-text-muted border-b border-white/[0.03] font-light">
                      <th className="text-left pb-1 font-light">Source</th>
                      <th className="text-right pb-1 font-light">Emissions (tCO₂e)</th>
                      <th className="text-right pb-1 font-light">% Total</th>
                      <th className="text-right pb-1 font-light">Trend</th>
                    </tr>
                  </thead>
                  <tbody>
                    {emissionSources.map((s, i) => (
                      <motion.tr key={s.name}
                        animate={{ backgroundColor: i === activeSource ? "rgba(34,197,94,0.03)" : "transparent" }}
                        className="text-[7.5px] border-b border-white/[0.01]"
                      >
                        <td className="py-1 text-text-secondary font-light flex items-center gap-1">
                          <span className="w-1 h-1 rounded-full opacity-80" style={{ background: breakdownData[i]?.color || "#6b7280" }} />
                          {s.name}
                        </td>
                        <td className="py-1 text-right font-mono text-text-primary font-light">{s.value}</td>
                        <td className="py-1 text-right font-mono text-text-muted font-light">{s.pct}</td>
                        <td className={`py-1 text-right font-mono font-light ${s.up ? "text-danger" : "text-accent/90"}`}>{s.trend}</td>
                      </motion.tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* AI Recommendations + Potential Reduction */}
              <div className="col-span-5 flex flex-col gap-2">
                <div className="rounded-lg bg-surface/40 border border-white/[0.03] p-2 flex-1 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-[9px] font-medium text-text-primary tracking-tight">AI Insights</span>
                      <span className="text-[6.5px] text-accent/80 hover:underline cursor-pointer font-light">View all</span>
                    </div>
                    <div className="rounded bg-[#0c0c0e] border border-white/[0.03] p-1.5 text-[7.5px] text-text-secondary font-light leading-relaxed">
                      Optimize Supplier B routing to reduce Scope 3 footprint by <span className="text-accent/90 font-medium">18.2%</span>.
                    </div>
                  </div>
                  <div className="flex gap-1 mt-1">
                    <span className="text-[6px] px-1 py-0.5 rounded bg-accent/5 text-accent/80 border border-accent/10 font-light">High Impact</span>
                    <span className="text-[6px] px-1 py-0.5 rounded bg-info/5 text-info/80 border border-info/10 font-light">Easy</span>
                  </div>
                </div>
                <div className="rounded-lg bg-surface/40 border border-white/[0.03] p-2">
                  <span className="text-[6.5px] text-text-muted font-light block">Calculated Reduction Opportunity</span>
                  <div className="flex items-baseline gap-0.5 mt-0.5">
                    <span className="text-[14px] font-medium font-mono text-accent/90 tracking-tight">1,248</span>
                    <span className="text-[7.5px] text-text-muted font-light">tCO₂e</span>
                  </div>
                </div>
              </div>
            </div>

            {/* ── Recent Activity Bar ── */}
            <div className="px-2 pb-2">
              <div className="rounded-lg bg-surface/20 border border-white/[0.03] px-2.5 py-1 flex items-center gap-3 overflow-hidden">
                <span className="text-[7.5px] text-text-muted font-medium shrink-0 uppercase tracking-wider">Live System Logs</span>
                <div className="flex items-center gap-3 overflow-hidden">
                  {recentActivity.map((a) => {
                    const Icon = a.icon;
                    return (
                      <div key={a.label} className="flex items-center gap-1 shrink-0 opacity-80">
                        <Icon className="h-2.5 w-2.5" style={{ color: a.color }} />
                        <span className="text-[7px] text-text-secondary font-light truncate max-w-[80px]">{a.label}</span>
                        <span className="text-[6px] text-text-muted font-light truncate max-w-[100px]">{a.sub}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
