import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions — Green Credit AI",
  description: "Green Credit AI Terms & Conditions. Rules governing use of the platform, AI services, and sustainability intelligence tools.",
};

export default function TermsPage() {
  return (
    <div className="text-text-primary">
      <div className="mb-10 pb-8 border-b border-white/[0.04]">
        <p className="text-[9px] text-accent/70 uppercase tracking-[0.3em] font-light mb-3">Legal</p>
        <h1 className="text-3xl font-light text-text-primary tracking-tight mb-3">Terms &amp; Conditions</h1>
        <p className="text-[12px] text-text-muted font-extralight">Effective date: 1 June 2026 · Last updated: 1 June 2026</p>
      </div>

      <div className="space-y-8 text-text-secondary font-extralight text-[13px] leading-relaxed">
        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using the Green Credit AI platform (greencredit.live), you agree to be bound by these Terms and Conditions. If you do not agree, please discontinue use of the platform immediately.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">2. Platform Description</h2>
          <p>Green Credit AI provides an AI-powered sustainability operating platform offering carbon analysis, ESG automation, greenwashing detection, supplier intelligence, and community sustainability engagement tools. The platform is provided for informational and operational purposes.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">3. User Responsibilities</h2>
          <p className="mb-3">You agree to:</p>
          <ul className="space-y-1.5 pl-4">
            {["Provide accurate sustainability and organizational data", "Not use the platform to make materially false or misleading environmental claims", "Maintain the security of your account credentials", "Comply with all applicable environmental reporting regulations", "Not reverse-engineer, scrape, or misuse platform AI systems"].map(item => (
              <li key={item} className="flex items-start gap-2"><span className="text-accent/40 mt-1.5 shrink-0">—</span>{item}</li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">4. AI-Generated Content</h2>
          <p>Sustainability insights, carbon calculations, ESG scores, and reports generated by our AI systems are provided as informational tools. They do not constitute legal, financial, or regulatory compliance advice. Users are responsible for verifying AI-generated content before filing official reports.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">5. Green Credits</h2>
          <p>Green Credits earned through verified sustainability actions are subject to our Green Credit Policy. Green Credits hold no guaranteed monetary value and are subject to platform rules. Fraudulent claims to earn Green Credits will result in account termination.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">6. Intellectual Property</h2>
          <p>All platform software, AI models, algorithms, designs, and content are the intellectual property of Green Credit AI. Users retain ownership of sustainability data they upload but grant us a license to process it for platform service delivery.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">7. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Green Credit AI is not liable for indirect, incidental, or consequential damages arising from platform use, AI output errors, or data processing inaccuracies.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">8. Governing Law</h2>
          <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">9. Contact</h2>
          <p>For questions about these Terms: <a href="mailto:hello@greencredit.live" className="text-accent/80 hover:text-accent transition-colors">hello@greencredit.live</a></p>
        </section>
      </div>
    </div>
  );
}
