import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — Green Credit AI",
  description: "Green Credit AI Disclaimer. Limitations on AI-generated sustainability analysis and environmental intelligence.",
};

export default function DisclaimerPage() {
  return (
    <div className="text-text-primary">
      <div className="mb-10 pb-8 border-b border-white/[0.04]">
        <p className="text-[9px] text-accent/70 uppercase tracking-[0.3em] font-light mb-3">Legal</p>
        <h1 className="text-3xl font-light text-text-primary tracking-tight mb-3">Disclaimer</h1>
        <p className="text-[12px] text-text-muted font-extralight">Effective date: 1 June 2026</p>
      </div>

      <div className="space-y-8 text-text-secondary font-extralight text-[13px] leading-relaxed">
        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">1. General Information</h2>
          <p>The information provided by Green Credit AI on greencredit.live and through our platform services is for general informational and operational purposes only. All information is provided in good faith, however we make no representation or warranty of any kind regarding its accuracy, completeness, or reliability.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">2. AI-Generated Analysis</h2>
          <p>Carbon calculations, ESG scores, greenwashing assessments, and sustainability insights generated by our AI systems are analytical tools, not regulatory determinations. They are based on the data inputs provided and the training data of our models. Users must independently verify AI outputs before using them for regulatory filings, investor disclosures, or legal purposes.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">3. No Professional Advice</h2>
          <p>Nothing on this platform constitutes legal, financial, regulatory compliance, or investment advice. For BRSR, GRI, TCFD, or SASB compliance filings, consult a qualified sustainability professional or legal advisor.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">4. Third-Party Data</h2>
          <p>Our platform may reference third-party databases, emission factors, and regulatory frameworks. We cannot guarantee the accuracy of third-party sources and are not responsible for any errors or omissions in referenced data.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">5. Platform Availability</h2>
          <p>We do not guarantee uninterrupted access to the platform. AI processing times, data availability, and feature sets may change without prior notice.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-light text-text-primary mb-3">6. Contact</h2>
          <p>For questions: <a href="mailto:hello@greencredit.live" className="text-accent/80 hover:text-accent transition-colors">hello@greencredit.live</a></p>
        </section>
      </div>
    </div>
  );
}
